/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class BitmapTest {
//  @Test public void testAppHasAGreeting() {
////    assertNotNull("app should have a greeting", App.getGreeting());
////  }
}
