/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {

  public static void main(String[] args) throws IOException {
  BufferedImage i  = ImageIO.read(new File(args[0]));
  Bitmap myBitmap  = new Bitmap(i);
  myBitmap.paintPurple();
  myBitmap.chnageToYellow();
  myBitmap.wtiteToFile(args[1]);
  }

  public static void main(String[] args) {
    File inputFile = new File("./src/main/resources/Coffee.bmp");

    // Call readFile method
    readFile(inputFile);

    // Set transformation of new bitmap 3 times
    // Bitmap.setTransformName();


  }


  public static void readFile(File path){
    File file = new File(String.valueOf(path));
    BufferedImage image = null;
    try{
      image = ImageIO.read(file);

      Bitmap b = new Bitmap(image);

      // write function and then call it on b
//      b.functionName()

      ImageIO.write(image, "bmp", new File("./src/main/resources/CoffeeCopy.bmp"));

      //create with input file, output file and transform
      System.out.println(image);
      System.out.println("Success!");
    } catch(IOException e){
      System.out.println("Something is wrong with the image file!");
    }
  }


}
